### ISSUE TITLE
Failed to install!!!

### ISSUE THREAD

**Issue by akanshSirohi** [hbldh/hitherdither#5]
* Python version: 3.7.4
* Operating System: Windows 10

### Description

Trying to install but it is showing some errors!

### What I Did

```
C:\Users\akans>pip install git+https://www.github.com/hbldh/hitherdither
Collecting git+https://www.github.com/hbldh/hitherdither
  Cloning https://www.github.com/hbldh/hitherdither to c:\users\akans\appdata\local\temp\pip-req-build-guyhoi6g
  Running command git clone -q https://www.github.com/hbldh/hitherdither 'C:\Users\akans\AppData\Local\Temp\pip-req-build-guyhoi6g'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Anaconda\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\akans\\AppData\\Local\\Temp\\pip-req-build-guyhoi6g\\setup.py'"'"'; __file__='"'"'C:\\Users\\akans\\AppData\\Local\\Temp\\pip-req-build-guyhoi6g\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\akans\AppData\Local\Temp\pip-req-build-guyhoi6g\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Anaconda\lib\site-packages\setuptools\__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "C:\Anaconda\lib\site-packages\setuptools\extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "C:\Anaconda\lib\site-packages\setuptools\dist.py", line 16, in <module>
        import pkg_resources
      File "C:\Anaconda\lib\site-packages\pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hbldh** [comment]
Either upgrade `setuptools` or downgrade it. Or upgrade pip? I don't know. 

Nothing in your stacktrace indicates that this is an error in `hitherdither` though.

**Comment by akanshSirohi** [comment]
Thanks @hbldh , I managed it by just including it in my project directory.
